### PR TITLE
fix BindMetaMixin with polymorphic

### PR DESCRIPTION
**Pull request by minisotm**
AttributeError: 'NoneType' object has no attribute 'info'
flask_sqlalchemy/model.py:124: AttributeError

How to reproduce:
   
   ```
bind_key = 'polymorphic_bind_key'

    app.config['SQLALCHEMY_BINDS'] = {
        bind_key: 'sqlite:///:memory',
    }

    class Base(db.Model):
        __bind_key__ = bind_key

        __tablename__ = 'base'

        id = db.Column(db.Integer, primary_key=True)

        p_type = db.Column(db.String(50))

        __mapper_args__ = {
            'polymorphic_identity': 'base',
            'polymorphic_on': p_type
        }

    class Child1(Base):

        child_1_data = db.Column(db.String(50))
        __mapper_args__ = {
            'polymorphic_identity': 'child_1',
        }
```

### CODE REVIEW

**Comment by davidism** [comment]
Thanks, this looks good. It's been a while since I looked at this, was this failing because `hasattr` was returning `True` but it was because `__table__ = None`?

**Comment by minisotm** [comment]
Yes, at this moment cls.__table__ is None, but attribute exists.

**Comment by davidism** [comment]
Would you add an entry in the changelog? Then I can merge.

**Comment by minisotm** [comment]
done

**Comment by minisotm** [comment]
Oops, version 2.3.2 or 2.3.3?

**Comment by davidism** [comment]
Hmm, didn't realize there wasn't a changelog already. Just create a new section with the next version number and no release date.

**Comment by dirkesquire** [comment]
I ran into exactly the same problem, so I need this fix.
I see you merged in a fix in October, but when will you be releasing it onto pypi.org?
Currently pypi.org is still showing 2.3.2.

**Pull request merged**
