### PR TITLE
Convert tests to pytest

### PR DESCRIPTION
**Pull request by thrawny**
For #363 

Removed `from __future__ import with_statement` when converting. As far as I can see, python 2.5 is not supported.

Ran tests using tox locally and `test_session_scoping_changing` sometimes fails with `py27-lowest`. Maybe someone can elaborate on this.

In `test_sessions.py` I set `flask.testing` to `False` since that is how it was in the original tests. Not sure if this is on purpose or not. If not then the overridden app fixture in that file is not needed.

Otherwise straight forward conversion using fixtures and so on.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Usually `tests` should not be a package.

**Comment by thrawny** [comment]
@ThiefMaster Was mainly due to wanting to import `make_todo_model`from somewhere. Should I make a separate file for it? Importing from `conftest`is ugly imo.

**Comment by ThiefMaster** [comment]
If it's a fixture in conftest.py you do not need to import it at all

**Comment by davidism** [comment]
You basically already have the fixture, inline `make_todo_model` into the `Todo` fixture.

**Comment by davidism** [comment]
For that test that constructs the model separately, just make a simple model in the test, you're not required to reuse that todo model everywhere.

**Comment by thrawny** [comment]
Yeah great, will fix that then.

**Comment by thrawny** [comment]
Removed `__init__.py` from `tests` and inlined the `Todo` model.

Had to change the `app` fixture a little bit to make other tests work. It get the current module name from the pytest request object and sets that as the app name.

**Comment by thrawny** [comment]
@davidism Had a change to look at the changes I made?

**Pull request merged**
