### PR TITLE
Fix issue #642: Record app when configuring it.

### PR DESCRIPTION
**Pull request by garenchan**
Fix issue #642.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
This isn't done on purpose because `init_app` can be used with multiple apps.

**Comment by garenchan** [comment]
@ThiefMaster， So why did SQLAlchemy records the app when I created it:
https://github.com/mitsuhiko/flask-sqlalchemy/blob/50944e77522d4aa005fc3c833b5a2042280686d3/flask_sqlalchemy/__init__.py#L675-L684

**Comment by ThiefMaster** [comment]
Because in *very* small apps that do not use an app factory this provides some convenience.

**Comment by garenchan** [comment]
The problem is that the two modes are inconsistent and you're not explaining them in the document.
Why don't you remove this statement from the constructor?
```
self.app = app 
```

**Pull request closed without merging**
