### PR TITLE
allow specifying custom meta class for declarative base

### PR DESCRIPTION
**Pull request by pbecotte**

### CODE REVIEW

**Comment by davidism** [comment]
I appreciate this, but I'm probably going to close it.  The amount of things getting passed in is becoming ridiculous (not your fault).  We need a better pattern for customizing all this.  Also, you didn't include any tests or documentation.

**Comment by immunda** [comment]
Agreed on both counts. Thank you though @pbecotte

**Comment by pbecotte** [comment]
No worries.  I was building this functionality for myself and thought I would open a pull request real quick to see if it would come in handy.  If you have ideas for a preferred way of handling this I would be happy to do a more complete job.

**Comment by davidism** [comment]
Currently, you can subclass the extension and override `make_declarative_base`.  We are discussing how to unify this in #357.

**Pull request closed without merging**
