### PR TITLE
Replace flask.ext.sqlalchemy with flask_sqlalchemy

### PR DESCRIPTION
**Pull request by ThiefMaster**

### CODE REVIEW

**Comment by jeffwidman** [comment]
:+1:

**Comment by davidism** [comment]
Can't believe I missed this, since I've been commenting about it everywhere else.  Thanks.

**Comment by immunda** [comment]
Glad to have this in, but was it confirmed not to break things as mentioned in #271 ?

**Comment by davidism** [comment]
I just verified that docs build correctly on Python 2.7.10 and 3.5.0.  All cross references work and the API is generated.

**Comment by immunda** [comment]
Perfect, ta.

**Pull request merged**
