### PR TITLE
optimization: paginate total count

### PR DESCRIPTION
**Pull request by doublefloat**

### CODE REVIEW

**Comment by davidism** [comment]
Is the optimization the elimination of the nested select that `.count()` renders?  It seems correct, but an explanation would be good just to be sure.

**Comment by doublefloat** [comment]
@davidism 
```
self.order_by(None).count() 
```
generates SQL like this: `select count(*) from (select abc, def from User) as u`
But we just expect `select count(*) from User`

**Comment by doublefloat** [comment]
`self.order_by(None).count()` will use temporary table in MySQL. It must be slower than direct selection.

**Comment by davidism** [comment]
I did an informal benchmark on a PostgreSQL system I have at work.  The new query either performed as well or worse than the current query.  I understand that the rendered statements are different, but I'm skeptical that the second performs better without some numbers to back it up.

**Comment by immunda** [comment]
Thanks @davidism. Significantly worse or within the margin of error?

@doublefloat Could you provide some numbers on a few different backends?

**Comment by doublefloat** [comment]
I made a test for each query on MySQL:
```
import suite

from sqlalchemy import func
from application.models import db
from application.models.user import User
import datetime

class TestCount(suite.BaseSuite):
    def test_count(self):
        with self.app.app_context():
            for i in range(10000):
                user = User(name="name_%s" % i, password='password')
                db.session.add(user)
                if i % 200 == 0:
                    db.session.commit()

            db.session.commit()

        with self.app.app_context():
            start = datetime.datetime.now()
            for i in range(1000):
                db.session.query(User).count()

            end = datetime.datetime.now()

            # 22.756345 sec
            print((end - start).total_seconds())

            start = datetime.datetime.now()
            query = db.session.query(User)
            for i in range(1000):
                db.session.execute(query.statement.with_only_columns([func.count(User.id)]).order_by(None)).scalar()

            end = datetime.datetime.now()

            # 5.668808 sec
            print((end - start).total_seconds())
```

First 1000 queris performed in 22.76 seconds, and the second 1000 queries in 5.67 seconds.

**Comment by RonnyPfannschmidt** [comment]
i have a a hunch that this optimization will break on some of the more complex queries that sqlalchemy allows - (details like combining aggregations with having clauses)

**Comment by davidism** [comment]
ping @zzzeek

**Comment by zzzeek** [comment]
I'd skip the session.execute(self.statement) aspect of it for sure, because it's unnecessary and you lose mapping information that is critical for session.get_bind(), and at least just say `query.order_by(None).value(func.count())`.   but also yes, the reason we do the subquery dance is because sometimes you need that subquery - for a long time we tried doing the query you see here when possible but as the edge cases kept coming in over the years, it eventually became not worth it to continue to guess when to subquery and when not to in all cases.    but you'd have to look up the history of this change to find those breakages, it's old stuff at this point.

**Comment by davidism** [comment]
Perhaps we add a `without_subquery=False` flag to `paginate`, with documentation warning that it might break certain complex queries when enabled.  Then it's up to the developer to construct their query appropriately and decide to enable the optimization.

**Comment by immunda** [comment]
Goodness. I'm tempted to break the pagination API in v3 and create a `Pagination` class, with a `count` method which could be overridden.

**Comment by davidism** [comment]
I agree, we should improve the pagination handling in general.  Extracting the pagination functions has already been brought up in #265.

There are [some open issues](https://github.com/mitsuhiko/flask-sqlalchemy/issues?utf8=%E2%9C%93&q=is%3Aopen+paginate) regarding pagination that could probably be handled at the same time.  This issue also duplicates #272.

**Comment by immunda** [comment]
Let's do it. I'll make a new issue for doing this properly and close up those.

**Comment by doublefloat** [comment]
@zzzeek Thank you for your information. It's thoughtless of me to change it.

**Comment by immunda** [comment]
No problem, thanks for taking the time to explore this anyway.

**Pull request closed without merging**
